-- SQL to create the MNDistrictData tables.  Make sure to create the MNDistrictData first! --

-- Create the district table
CREATE TABLE district (
	id SERIAL PRIMARY KEY,
	name VARCHAR,
	county INTEGER,
	region VARCHAR,
	number INTEGER,
	type INTEGER,
	total_enrollment_14_15  INTEGER,
	female_14_15 INTEGER,
	male_14_15 INTEGER,
	amer_indian_14_15 INTEGER,
	asian_pacific_islander_14_15 INTEGER,
	hispanic_14_15 INTEGER,
	black_14_15 INTEGER,
	white_14_15 INTEGER,
	multi_race_14_15 INTEGER,
	grade_k_5_14_15 INTEGER,
	grade_6_8_14_15 INTEGER,
	grade_9_12_14_15 INTEGER,
	total_enrollment_15_16 INTEGER,
	female_15_16 INTEGER,
	male_15_16 INTEGER,
	amer_indian_15_16 INTEGER,
	asian_pacific_islander_15_16 INTEGER,
	hispanic_15_16 INTEGER,
	black_15_16 INTEGER,
	white_15_16 INTEGER,
	multi_race_15_16 INTEGER,
	grade_k_5_15_16 INTEGER,
	grade_6_8_15_16 INTEGER,
	grade_9_12_15_16 INTEGER,
	total_enrollment_16_17 INTEGER,
	female_16_17 INTEGER,
	male_16_17 INTEGER,
	amer_india_16_17 INTEGER,
	asian_pacific_islander_16_17 INTEGER,
	hispanic_16_17 INTEGER,
	black_16_17 INTEGER,
	white_16_17 INTEGER,
	multi_race_16_17 INTEGER,
	grade_k_5_16_17 INTEGER,
	grade_6_8_16_17 INTEGER,
	grade_9_12_16_17 INTEGER,
	total_enrollment_17_18 INTEGER,
	female_17_18 INTEGER,
	male_17_18 INTEGER,
	amer_indian_17_18 INTEGER,
	asian_pacific_islander_17_18 INTEGER,
	hispanic_17_18 INTEGER,
	black_17_18 INTEGER,
	white_17_18 INTEGER,
	multi_race_17_18 INTEGER,
	grade_k_5_17_18 INTEGER,
	grade_6_8_17_18 INTEGER,
	grade_9_12_17_18 INTEGER,
	total_enrollment_18_19 INTEGER,
	female_18_19 INTEGER,
	male_18_19 INTEGER,
	amer_indian_18_19 INTEGER,
	asian_pacific_islander_18_19 INTEGER,
	hispanic_18_19 INTEGER,
	black_18_19 INTEGER,
	white_18_19 INTEGER,
	multi_race_18_19 INTEGER,
	grade_k_5_18_19 INTEGER,
	grade_6_9_18_19 INTEGER,
	grade_9_12_18_19 INTEGER
);

-- Create the incident table
CREATE TABLE incident (
	id SERIAL PRIMARY KEY,
	district_id INTEGER,
	school_year VARCHAR,
	alcohol INTEGER,
	arson INTEGER,
	assault INTEGER,
	attendance INTEGER,
	bomb INTEGER,
	bomb_threat INTEGER,
	bullying INTEGER,
	computer INTEGER,
	controlled_substances INTEGER,
	cyber_bullying INTEGER,
	disruptive_disorderly INTEGER,
	extortion INTEGER,
	fighting INTEGER,
	gang_activity INTEGER,
	harassment INTEGER,
	hazing INTEGER,
	homicide INTEGER,
	illegal_drugs INTEGER,
	over_the_counter_meds INTEGER,
	pyrotechnics INTEGER,
	robbery_using_force INTEGER,
	terroristic_threats INTEGER,
	theft INTEGER,
	threat_intimidation INTEGER,
	tobacco INTEGER,
	vandalism INTEGER,
	verbal_abuse INTEGER,
	weapon INTEGER,
	other INTEGER,
	FOREIGN KEY (district_id) REFERENCES district(id)
);

--  Create the incident by gender table
CREATE TABLE incident_by_gender (
	id SERIAL PRIMARY KEY,
	district_id INTEGER,
	school_year VARCHAR,
	female INTEGER,
	male INTEGER,
	FOREIGN KEY (district_id) REFERENCES district(id)
);

-- Create the incident by grade table
CREATE TABLE incident_by_grade (
	id SERIAL PRIMARY KEY,
	district_id INTEGER,
	school_year VARCHAR,
	grade_k_5 INTEGER,
	grade_6_8 INTEGER,
	grade_9_12 INTEGER,
	FOREIGN KEY (district_id) REFERENCES district(id)
);

-- Create the incident by race table
CREATE TABLE incident_by_race (
	id SERIAL PRIMARY KEY,
	district_id INTEGER,
	school_year VARCHAR,
	amer_indian INTEGER,
	asian_pacific_islander INTEGER,
	black INTEGER,
	hispanic INTEGER,
	white INTEGER,
	multi_race INTEGER,
	FOREIGN KEY (district_id) REFERENCES district(id)
);